NUM=[10,20,30,40,50]
print(NUM,type(NUM))
print("accessing the list elements using +ve indexing")
print(NUM[0])
print(NUM[1])
print(NUM[2])
print(NUM[3])
print(NUM[4])
print("accessing the list elements using -ve indexing")
print(NUM[-5])
print(NUM[-4])
print(NUM[-3])
print(NUM[-2])
print(NUM[-1])